/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const InquiryType = IDL.Variant({
  'contact' : IDL.Null,
  'serviceRequest' : IDL.Null,
});
export const Time = IDL.Int;
export const Inquiry = IDL.Record({
  'id' : IDL.Nat,
  'serviceCategory' : IDL.Opt(IDL.Text),
  'internal' : IDL.Bool,
  'inquiryType' : InquiryType,
  'name' : IDL.Text,
  'email' : IDL.Opt(IDL.Text),
  'message' : IDL.Text,
  'timestamp' : Time,
  'phoneNumber' : IDL.Text,
});
export const UserProfile = IDL.Record({ 'name' : IDL.Text });

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'deleteInquiry' : IDL.Func([IDL.Nat], [], []),
  'getAllInquiries' : IDL.Func([], [IDL.Vec(Inquiry)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getFirstPublicInquiries' : IDL.Func(
      [IDL.Nat],
      [IDL.Vec(Inquiry)],
      ['query'],
    ),
  'getFirstPublicInternalInquiries' : IDL.Func(
      [IDL.Nat],
      [IDL.Vec(Inquiry)],
      ['query'],
    ),
  'getInquiry' : IDL.Func([IDL.Nat], [Inquiry], ['query']),
  'getPublicInquiries' : IDL.Func([], [IDL.Vec(Inquiry)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'submitInquiry' : IDL.Func(
      [
        InquiryType,
        IDL.Text,
        IDL.Text,
        IDL.Opt(IDL.Text),
        IDL.Text,
        IDL.Opt(IDL.Text),
      ],
      [IDL.Nat],
      [],
    ),
  'submitInternalInquiry' : IDL.Func(
      [
        InquiryType,
        IDL.Text,
        IDL.Text,
        IDL.Opt(IDL.Text),
        IDL.Text,
        IDL.Opt(IDL.Text),
      ],
      [IDL.Nat],
      [],
    ),
  'updateInquiry' : IDL.Func([IDL.Nat, Inquiry], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const InquiryType = IDL.Variant({
    'contact' : IDL.Null,
    'serviceRequest' : IDL.Null,
  });
  const Time = IDL.Int;
  const Inquiry = IDL.Record({
    'id' : IDL.Nat,
    'serviceCategory' : IDL.Opt(IDL.Text),
    'internal' : IDL.Bool,
    'inquiryType' : InquiryType,
    'name' : IDL.Text,
    'email' : IDL.Opt(IDL.Text),
    'message' : IDL.Text,
    'timestamp' : Time,
    'phoneNumber' : IDL.Text,
  });
  const UserProfile = IDL.Record({ 'name' : IDL.Text });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'deleteInquiry' : IDL.Func([IDL.Nat], [], []),
    'getAllInquiries' : IDL.Func([], [IDL.Vec(Inquiry)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getFirstPublicInquiries' : IDL.Func(
        [IDL.Nat],
        [IDL.Vec(Inquiry)],
        ['query'],
      ),
    'getFirstPublicInternalInquiries' : IDL.Func(
        [IDL.Nat],
        [IDL.Vec(Inquiry)],
        ['query'],
      ),
    'getInquiry' : IDL.Func([IDL.Nat], [Inquiry], ['query']),
    'getPublicInquiries' : IDL.Func([], [IDL.Vec(Inquiry)], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'submitInquiry' : IDL.Func(
        [
          InquiryType,
          IDL.Text,
          IDL.Text,
          IDL.Opt(IDL.Text),
          IDL.Text,
          IDL.Opt(IDL.Text),
        ],
        [IDL.Nat],
        [],
      ),
    'submitInternalInquiry' : IDL.Func(
        [
          InquiryType,
          IDL.Text,
          IDL.Text,
          IDL.Opt(IDL.Text),
          IDL.Text,
          IDL.Opt(IDL.Text),
        ],
        [IDL.Nat],
        [],
      ),
    'updateInquiry' : IDL.Func([IDL.Nat, Inquiry], [], []),
  });
};

export const init = ({ IDL }) => { return []; };